# Generated by Django 4.1.7 on 2023-03-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scribble', models.ImageField(upload_to='scribbles', verbose_name='Scribble')),
                ('prompt', models.CharField(max_length=60, verbose_name='Prompt')),
                ('generatedImage', models.ImageField(blank=True, upload_to='generated', verbose_name='GeneratedImage')),
            ],
        ),
    ]
