# Generated by Django 4.1 on 2023-03-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='prompt',
            field=models.CharField(max_length=200, verbose_name='Prompt'),
        ),
    ]
